version: '3'

services:
  prometheus:
    restart: always
    image: prom/prometheus
    command: --config.file=/prometheus/prometheus.yml --storage.tsdb.path=/prometheus/db/ --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/prometheus

  grafana:
    restart: always
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
